import { NextRequest, NextResponse } from "next/server";
import { adminGql } from "@/lib/nhost";
import { cookies } from "next/headers";
import { USERS, resolveOrgId } from "@/lib/orgs";

const UPDATE_WORKFLOW_MUTATION = `
  mutation UpdateWorkflow(
    $id: uuid!
    $name: String!
    $description: String
    $is_active: Boolean!
    $step_ids_to_keep: [uuid!]!
    $steps: [workflow_steps_insert_input!]!
  ) {
    update_workflows_by_pk(
      pk_columns: { id: $id },
      _set: { name: $name, description: $description, is_active: $is_active }
    ) {
      id
    }
    
    delete_workflow_steps(
      where: {
        workflow_id: { _eq: $id },
        id: { _nin: $step_ids_to_keep }
      }
    ) {
      affected_rows
    }

    insert_workflow_steps(
      objects: $steps,
      on_conflict: {
        constraint: workflow_steps_pkey,
        update_columns: [step_order, type, label, config]
      }
    ) {
      affected_rows
    }
  }
`;

export async function POST(req: NextRequest) {
  try {
    const { workflow_id, name, description, is_active, steps } = await req.json();

    if (!workflow_id || !name) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const step_ids_to_keep = steps.map((s: any) => s.id).filter(Boolean);

    // Prepare steps for insert/upsert
    const stepInserts = steps.map((s: any, i: number) => ({
      id: s.id || undefined, // undefined means it will be generated by db if not provided
      workflow_id,
      step_order: i + 1,
      type: s.type,
      label: s.label,
      config: s.config,
    }));

    const result = await adminGql(UPDATE_WORKFLOW_MUTATION, {
      id: workflow_id,
      name,
      description: description || null,
      is_active: is_active ?? true,
      step_ids_to_keep,
      steps: stepInserts,
    });

    return NextResponse.json({ success: true, result });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
